### ISSUE TITLE
Validation fails with uppercase characters in label key

### ISSUE THREAD

**Issue by kenfinnigan** [OpenSLO/oslo#128]
### Summary

Validation of label keys in metadata fails with an uppercase character in the name.

### What is the current *bug* behavior?

SLO yaml with the following content will fail validation:

```
metadata:
  name: string
  displayName: string # optional
  labels:
    userImpacting:
      - "true"
```

### What is the expected *correct* behavior?

Validation succeeds

### Possible fixes

The check [here](https://github.com/OpenSLO/oslo/blob/main/internal/pkg/validate/validate.go#L224) can be removed to allow uppercase characters in the label key. As per https://github.com/openslo/openslo#general-schema it should be possible
