### ISSUE TITLE
breaking change in default behaviour I'm relaying on and seems relevant property it's not configurable

### ISSUE THREAD

**Issue by n0npax** [OpenSLO/oslo#194]
### Summary

Please consider [PR-187](https://github.com/OpenSLO/oslo/pull/187) as relevant source.

Within nobl9 indicator kind keyword `"Direct"` was replaced by `"Agent"`. This changes default `oslo` behaviour I was relying on.

old code was assuming given hardcode:

```
		return nobl9v1alpha.Indicator{
			MetricSource: nobl9v1alpha.MetricSourceSpec{
				Kind:    "Direct", # <---------
				Name:    rmt,
				Project: project,
			},
```
but new one is
```
			return nobl9v1alpha.Indicator{
				MetricSource: nobl9v1alpha.MetricSourceSpec{
					Project: metricSourceProject,
					Name:    name,
					Kind:    "Agent", # <----------
				},
```

Please also consider given [codeblck](https://github.com/OpenSLO/oslo/pull/187/files#diff-8f9b223b72569b1b5a758d2828bf9e6f0b6e357afb8154fc2ddd59df3df71ed6R235-R240):

```
	// Since we don't have a way of specifying MetricSource.Kind in OpenSLO, use Nobl9's default
	// of Agent, and warn the user
	_ = printWarning(
		"We don't have a way of specifying the MetricSource Kind (Agent or Direct) in OpenSLO " +
			"so we will use Nobl9's default of Agent",
	)
```

With current state I believe I can't adjust my config to change `kind` type on demand and new default value doesn't work for me.

### Steps to reproduce

Convert `openSLO` to `nobl9` SLO within splunk based metrics.
```sh
 oslo convert -f ${INPUT_SLO}.yaml -f ${INPUT_SERVICE}.yaml -o nobl9 -p llama
```

### What is the current *bug* behavior?

Tool generates invalid nobl9 SLO and warns user.

### What is the expected *correct* behavior?

- [ ] Ability to specify `"Direct"` or `"Agent"` on demand (preferred)
- [ ] Change of default value to `"Direct"` (less preferred)

### Relevant logs and/or screenshots

Sample relevant piece of output I can generate looks like:

```
---
apiVersion: n9/v1alpha
kind: SLO
metadata:
  name: foo-availability
  project: llama
  ...
spec:
  indicator:
    metricSource:
      name: ChangeMe # <—---- Problem with generated output is here
      kind: ""
     ....
```

using old version of `oslo`(docker image with tag `sha-0ef3a32`) I'm able to get indicator value with expected data.

```
      indicator:
          metricSource:
              project: redacted
              name: redacted
              kind: Direct
```

Redacted `slo` which can be used to test behaviour looks like: 

```
apiVersion: openslo/v1
kind: SLO
metadata:
  name: redacted
  displayName: redacted [availability]
  # labels:
    # redacted
  #annotations:
    # redacted
spec:
  description: 'redacted http://example.com/FIXME'
  service: redacted
  indicator:
    metadata:
      name: redacted
      labels: {}
      annotations: {}
    spec:
      ratioMetric:
        counter: true
        good:
          metricSource:
            metricSourceRef: redacted
            type: Splunk
            spec:
              query: redacted
        total:
          metricSource:
            metricSourceRef: redacted
            type: Splunk
            spec:
              query: redacted
  budgetingMethod: Occurrences
  timeWindow:
    - duration: 28d
      isRolling: true
  objectives:
    - displayName: good
      value: 1
      target: 0.987654321
  alertPolicies: []
  ```
