### ISSUE TITLE
Support labels with multiple values for a single key as described in OpenSLO spec 

### ISSUE THREAD

**Issue by programmer04** [OpenSLO/oslo#202]
### Problem to solve

Currently, `oslo` supports only labels in the below format
```yml
...
metadata:
  labels:
    team: "a"
...
```
check [the source code](https://github.com/OpenSLO/oslo/blob/main/pkg/manifest/v1/objects.go#L92).

OpenSLO spec allows to define them as
```yml
...
metadata:
  labels:
    team:
      - "a"
      - "b"
...
```
too. 

### Proposal

Let's support both ways. Don't break the current workflow with oslo.

### Further details

Under the hood, it should always be unmarshaled into `[]string`. [It's doable with the current YAML library](https://github.com/go-yaml/yaml/issues/100#issuecomment-901604971).
